//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Protobuf3.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ProtoBuf.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Protobuf3Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IProtobuf3Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProto([NotNull] Protobuf3Parser.ProtoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyntax([NotNull] Protobuf3Parser.SyntaxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.optionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionStatement([NotNull] Protobuf3Parser.OptionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionName([NotNull] Protobuf3Parser.OptionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldLabel([NotNull] Protobuf3Parser.FieldLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] Protobuf3Parser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneof([NotNull] Protobuf3Parser.OneofContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofField([NotNull] Protobuf3Parser.OneofFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapField([NotNull] Protobuf3Parser.MapFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyType([NotNull] Protobuf3Parser.KeyTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_([NotNull] Protobuf3Parser.Type_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReserved([NotNull] Protobuf3Parser.ReservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRanges([NotNull] Protobuf3Parser.RangesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.range_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_([NotNull] Protobuf3Parser.Range_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.reservedFieldNames"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReservedFieldNames([NotNull] Protobuf3Parser.ReservedFieldNamesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDef([NotNull] Protobuf3Parser.EnumDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumElement([NotNull] Protobuf3Parser.EnumElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumField([NotNull] Protobuf3Parser.EnumFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumValueOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueOptions([NotNull] Protobuf3Parser.EnumValueOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageDef([NotNull] Protobuf3Parser.MessageDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageElement([NotNull] Protobuf3Parser.MessageElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.extendDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtendDef([NotNull] Protobuf3Parser.ExtendDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.serviceDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceDef([NotNull] Protobuf3Parser.ServiceDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.serviceElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceElement([NotNull] Protobuf3Parser.ServiceElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRpc([NotNull] Protobuf3Parser.RpcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] Protobuf3Parser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.blockLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockLit([NotNull] Protobuf3Parser.BlockLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.emptyStatement_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement_([NotNull] Protobuf3Parser.EmptyStatement_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdent([NotNull] Protobuf3Parser.IdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullIdent([NotNull] Protobuf3Parser.FullIdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageName([NotNull] Protobuf3Parser.MessageNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumName([NotNull] Protobuf3Parser.EnumNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldName([NotNull] Protobuf3Parser.FieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofName([NotNull] Protobuf3Parser.OneofNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapName([NotNull] Protobuf3Parser.MapNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitServiceName([NotNull] Protobuf3Parser.ServiceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRpcName([NotNull] Protobuf3Parser.RpcNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageType([NotNull] Protobuf3Parser.MessageTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.enumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumType([NotNull] Protobuf3Parser.EnumTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.intLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLit([NotNull] Protobuf3Parser.IntLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.strLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrLit([NotNull] Protobuf3Parser.StrLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.boolLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLit([NotNull] Protobuf3Parser.BoolLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.floatLit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLit([NotNull] Protobuf3Parser.FloatLitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Protobuf3Parser.keywords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeywords([NotNull] Protobuf3Parser.KeywordsContext context);
}
} // namespace ProtoBuf.Antlr
