//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Protobuf3.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ProtoBuf.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProtobuf3Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Protobuf3BaseListener : IProtobuf3Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProto([NotNull] Protobuf3Parser.ProtoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.proto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProto([NotNull] Protobuf3Parser.ProtoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax([NotNull] Protobuf3Parser.SyntaxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax([NotNull] Protobuf3Parser.SyntaxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStatement([NotNull] Protobuf3Parser.ImportStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.packageStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackageStatement([NotNull] Protobuf3Parser.PackageStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.optionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionStatement([NotNull] Protobuf3Parser.OptionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.optionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionStatement([NotNull] Protobuf3Parser.OptionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionName([NotNull] Protobuf3Parser.OptionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.optionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionName([NotNull] Protobuf3Parser.OptionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldLabel([NotNull] Protobuf3Parser.FieldLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldLabel([NotNull] Protobuf3Parser.FieldLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] Protobuf3Parser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] Protobuf3Parser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOptions([NotNull] Protobuf3Parser.FieldOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOption([NotNull] Protobuf3Parser.FieldOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldNumber([NotNull] Protobuf3Parser.FieldNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneof([NotNull] Protobuf3Parser.OneofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneof([NotNull] Protobuf3Parser.OneofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneofField([NotNull] Protobuf3Parser.OneofFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneofField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneofField([NotNull] Protobuf3Parser.OneofFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapField([NotNull] Protobuf3Parser.MapFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.mapField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapField([NotNull] Protobuf3Parser.MapFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyType([NotNull] Protobuf3Parser.KeyTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.keyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyType([NotNull] Protobuf3Parser.KeyTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_([NotNull] Protobuf3Parser.Type_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_([NotNull] Protobuf3Parser.Type_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReserved([NotNull] Protobuf3Parser.ReservedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReserved([NotNull] Protobuf3Parser.ReservedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRanges([NotNull] Protobuf3Parser.RangesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRanges([NotNull] Protobuf3Parser.RangesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.range_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange_([NotNull] Protobuf3Parser.Range_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.range_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange_([NotNull] Protobuf3Parser.Range_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.reservedFieldNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReservedFieldNames([NotNull] Protobuf3Parser.ReservedFieldNamesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.reservedFieldNames"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReservedFieldNames([NotNull] Protobuf3Parser.ReservedFieldNamesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.topLevelDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelDef([NotNull] Protobuf3Parser.TopLevelDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDef([NotNull] Protobuf3Parser.EnumDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDef([NotNull] Protobuf3Parser.EnumDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBody([NotNull] Protobuf3Parser.EnumBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumElement([NotNull] Protobuf3Parser.EnumElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumElement([NotNull] Protobuf3Parser.EnumElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumField([NotNull] Protobuf3Parser.EnumFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumField([NotNull] Protobuf3Parser.EnumFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumValueOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValueOptions([NotNull] Protobuf3Parser.EnumValueOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumValueOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValueOptions([NotNull] Protobuf3Parser.EnumValueOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumValueOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValueOption([NotNull] Protobuf3Parser.EnumValueOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageDef([NotNull] Protobuf3Parser.MessageDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageDef([NotNull] Protobuf3Parser.MessageDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageBody([NotNull] Protobuf3Parser.MessageBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageElement([NotNull] Protobuf3Parser.MessageElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageElement([NotNull] Protobuf3Parser.MessageElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.extendDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendDef([NotNull] Protobuf3Parser.ExtendDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.extendDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendDef([NotNull] Protobuf3Parser.ExtendDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.serviceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterServiceDef([NotNull] Protobuf3Parser.ServiceDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.serviceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitServiceDef([NotNull] Protobuf3Parser.ServiceDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.serviceElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterServiceElement([NotNull] Protobuf3Parser.ServiceElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.serviceElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitServiceElement([NotNull] Protobuf3Parser.ServiceElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRpc([NotNull] Protobuf3Parser.RpcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.rpc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRpc([NotNull] Protobuf3Parser.RpcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] Protobuf3Parser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] Protobuf3Parser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.blockLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockLit([NotNull] Protobuf3Parser.BlockLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.blockLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockLit([NotNull] Protobuf3Parser.BlockLitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.emptyStatement_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement_([NotNull] Protobuf3Parser.EmptyStatement_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.emptyStatement_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement_([NotNull] Protobuf3Parser.EmptyStatement_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdent([NotNull] Protobuf3Parser.IdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdent([NotNull] Protobuf3Parser.IdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFullIdent([NotNull] Protobuf3Parser.FullIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fullIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFullIdent([NotNull] Protobuf3Parser.FullIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageName([NotNull] Protobuf3Parser.MessageNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageName([NotNull] Protobuf3Parser.MessageNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumName([NotNull] Protobuf3Parser.EnumNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumName([NotNull] Protobuf3Parser.EnumNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldName([NotNull] Protobuf3Parser.FieldNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldName([NotNull] Protobuf3Parser.FieldNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneofName([NotNull] Protobuf3Parser.OneofNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.oneofName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneofName([NotNull] Protobuf3Parser.OneofNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapName([NotNull] Protobuf3Parser.MapNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.mapName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapName([NotNull] Protobuf3Parser.MapNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterServiceName([NotNull] Protobuf3Parser.ServiceNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.serviceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitServiceName([NotNull] Protobuf3Parser.ServiceNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRpcName([NotNull] Protobuf3Parser.RpcNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.rpcName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRpcName([NotNull] Protobuf3Parser.RpcNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageType([NotNull] Protobuf3Parser.MessageTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.messageType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageType([NotNull] Protobuf3Parser.MessageTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.enumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumType([NotNull] Protobuf3Parser.EnumTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.enumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumType([NotNull] Protobuf3Parser.EnumTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.intLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntLit([NotNull] Protobuf3Parser.IntLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.intLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntLit([NotNull] Protobuf3Parser.IntLitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.strLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrLit([NotNull] Protobuf3Parser.StrLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.strLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrLit([NotNull] Protobuf3Parser.StrLitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.boolLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolLit([NotNull] Protobuf3Parser.BoolLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.boolLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolLit([NotNull] Protobuf3Parser.BoolLitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.floatLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLit([NotNull] Protobuf3Parser.FloatLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.floatLit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLit([NotNull] Protobuf3Parser.FloatLitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Protobuf3Parser.keywords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeywords([NotNull] Protobuf3Parser.KeywordsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Protobuf3Parser.keywords"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeywords([NotNull] Protobuf3Parser.KeywordsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ProtoBuf.Antlr
